from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('resources/', views.resources, name='resources'),
    path('resources/student-guide/', views.student_guide, name='student_guide'),
    path('resources/course-descriptions/', views.course_descriptions, name='course_descriptions'),
    path('apply', views.apply, name='apply'),
    path('parking', views.parking_application, name='parking_application'),
    path('exchange', views.exchange_program, name='exchange_program'),
    path('exchange/application/', views.exchange_application, name='exchange_application'),
    path('members', views.members, name='members'),
    path('deanslist', views.deanslist, name='deanslist'),
    path('contact', views.contact, name='contact'),
    path('contact/thread/<int:thread_id>/', views.thread_detail, name='thread_detail'),
    path('contact/thread/<int:thread_id>/reply/', views.add_reply, name='add_reply'),
    path('contact/thread/<int:thread_id>/delete/', views.delete_thread, name='delete_thread'),
    path('contact/reply/<int:reply_id>/delete/', views.delete_reply, name='delete_reply'),
    path('portal', views.portal, name='portal'),
    path('events/', views.events_list, name='events'),
    path('events/<int:pk>/', views.event_detail, name='event_detail'),
    path('events/create/', views.create_event, name='create_event'),
    path('image-proxy/', views.image_proxy, name='image_proxy'),
    path('events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    # dynamic start/end verification routes using three preset secret numbers each
    path('events/verify/start/<int:a>/<int:b>/<int:c>/', views.verify_start, name='verify_start'),
    path('events/verify/end/<int:a>/<int:b>/<int:c>/', views.verify_end, name='verify_end'),
    path('events/<int:pk>/attendance-qr/', views.attendance_qr, name='attendance_qr'),
    path('events/<int:pk>/manage-sections/', views.manage_event_sections, name='manage_event_sections'),
    path('register', views.register, name='register'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path('portal/newdl', views.newdl, name='newdl'),
    path('portal/student-search', views.student_search, name='student_search'),
    path('portal/applications', views.application_management, name='application_management'),
    path('portal/applications/delete/<int:application_id>/', views.delete_application, name='delete_application'),
    path('portal/applications/delete-all/', views.delete_all_applications, name='delete_all_applications'),
    path('portal/parking', views.parking_management, name='parking_management'),
    path('portal/parking/delete/<int:application_id>/', views.delete_parking_application, name='delete_parking_application'),
    path('portal/parking/delete-all/', views.delete_all_parking_applications, name='delete_all_parking_applications'),
    path('portal/add-member', views.add_member, name='add_member'),
    path('portal/manage-members', views.manage_members, name='manage_members'),
    path('portal/exchange-dashboard/', views.exchange_dashboard, name='exchange_dashboard'),
    path('portal/exchange-applications/', views.exchange_application_management, name='exchange_application_management'),
    path('portal/exchange-nominations/', views.exchange_officer_dashboard, name='exchange_officer_dashboard'),
    path('portal/exchange-applications/<int:application_id>/toggle/', views.toggle_exchange_application_archive, name='toggle_exchange_application_archive'),
    path('portal/exchange-nominations/<int:nomination_id>/toggle/', views.toggle_exchange_nomination_archive, name='toggle_exchange_nomination_archive'),
    path('portal/members/update-role/<int:user_id>/', views.update_member_role, name='update_member_role'),
    path('portal/members/delete/<int:user_id>/', views.delete_member, name='delete_member'),
    path('portal/thread-settings', views.thread_settings, name='thread_settings'),
    path('portal/exchange-settings', views.exchange_program_settings, name='exchange_program_settings'),
    path('portal/refresh-courses', views.refresh_courses, name='refresh_courses'),
    path('portal/refresh-courses/progress', views.refresh_courses_progress, name='refresh_courses_progress'),
    path('portal/refresh-courses/status', views.refresh_courses_status, name='refresh_courses_status'),
    path('portal/events-dashboard', views.events_dashboard, name='events_dashboard'),
    path('portal/events/<int:pk>/attendance-data/', views.event_attendance_data, name='event_attendance_data'),
    path('portal/events/<int:pk>/export-sections/', views.export_event_sections, name='export_event_sections'),
    path('portal/database/backup/', views.backup_database, name='backup_database'),
    path('portal/database/restore/', views.restore_database, name='restore_database'),
    path('portal/merged-deans-list/', views.merged_deans_list, name='merged_deans_list'),
    # Test route for 404 page
    path('test-404/', views.custom_404_view, name='test_404'),
]
