# Generated by Django 5.2.5 on 2025-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_member_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SECRETARY', 'General Secretary'), ('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('TREASURER', 'Treasurer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
