# Generated by Django 5.2.5 on 2025-09-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanListStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('passed_credits', models.IntegerField()),
                ('registered_credits', models.IntegerField()),
                ('excel_file', models.FileField(upload_to='dean_list_excel_files/')),
            ],
        ),
    ]
