# Generated by Django 5.2.5 on 2025-09-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deanliststudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanliststudent',
            name='excel_file',
        ),
        migrations.CreateModel(
            name='DeanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=10)),
                ('year', models.IntegerField()),
                ('excel_file', models.FileField(upload_to='dean_list_excel_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('semester', 'year')},
            },
        ),
    ]
