# Generated by Django 5.2.5 on 2025-09-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_deanliststudent_excel_file_deanlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanliststudent',
            name='student',
        ),
        migrations.AddField(
            model_name='deanliststudent',
            name='dean_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.deanlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deanliststudent',
            name='student_id',
            field=models.CharField(default=9, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deanliststudent',
            name='student_major',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deanliststudent',
            name='student_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
