# Generated by Django 5.2.5 on 2025-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_deanliststudent_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='passed_credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
