# Generated by Django 5.2.5 on 2025-09-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_thread_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_new_threads', models.BooleanField(default=True)),
                ('closure_message', models.TextField(blank=True, default='Thread creation is temporarily disabled. Please check back later.', help_text='Message to display when thread creation is disabled')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread Settings',
                'verbose_name_plural': 'Thread Settings',
            },
        ),
    ]
