# Generated by Django 5.2.5 on 2025-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_threadsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Course ID (e.g., FIN301)', max_length=20, unique=True)),
                ('course_name', models.CharField(help_text='Full course name', max_length=255)),
                ('syllabus_url', models.URLField(blank=True, help_text='Direct download link to syllabus PDF', null=True)),
                ('info_url', models.URLField(blank=True, help_text='URL to course info page', null=True)),
                ('department', models.CharField(blank=True, help_text='Department code (FIN, MKT, etc.)', max_length=10, null=True)),
                ('credits', models.IntegerField(blank=True, help_text='Number of credit hours', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently offered')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the course data was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_id'],
            },
        ),
    ]
