# Generated by Django 5.2.5 on 2025-10-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_attendance_add_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
