# Generated by Django 5.2.5 on 2025-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_event_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'code'), ('event', 'student_id')},
        ),
    ]
