# Generated by Django 5.2.5 on 2025-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='secret_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
