# Generated by Django 5.2.5 on 2025-10-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event_secret_a_event_secret_b_event_secret_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='secret_a',
        ),
        migrations.RemoveField(
            model_name='event',
            name='secret_b',
        ),
        migrations.RemoveField(
            model_name='event',
            name='secret_c',
        ),
        migrations.AddField(
            model_name='event',
            name='secret_end_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_end_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_end_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_start_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_start_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_start_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
