# Generated by Django 5.2.5 on 2025-10-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_event_secret_a_remove_event_secret_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=200)),
                ('section_code', models.CharField(help_text='e.g., ACC201-001 or Section 1', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.event')),
            ],
            options={
                'ordering': ['section_code'],
                'unique_together': {('event', 'section_code')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='main.eventsection'),
        ),
    ]
