# Generated by Django 5.2.5 on 2025-10-15 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_partner_university_and_exchange_updates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeApplication',
        ),
        migrations.CreateModel(
            name='ExchangeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('home_major', models.CharField(max_length=150)),
                ('program_level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate')], max_length=20)),
                ('exchange_semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10)),
                ('exchange_academic_year', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other / Prefer not to say')], max_length=10)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('completed_credits', models.PositiveIntegerField()),
                ('english_proficiency_document', models.FileField(upload_to='exchange_applications/english/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('transcript_document', models.FileField(upload_to='exchange_applications/transcripts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('passport_copy', models.FileField(upload_to='exchange_applications/passports/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('accommodation_needed', models.BooleanField(default=False)),
                ('has_criminal_record', models.BooleanField(default=False)),
                ('coordinator_name', models.CharField(max_length=150)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('is_archived', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('home_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_applications', to='main.partneruniversity')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SECRETARY', 'General Secretary'), ('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('TREASURER', 'Treasurer'), ('EXCHANGE_OFFICER', 'Exchange Officer')], max_length=20),
        ),
    ]
