# Generated by Django 5.2.5 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_is_archived_to_exchange_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('major', models.CharField(choices=[('FIN', 'Finance'), ('MIS', 'Management Information Systems'), ('MKT', 'Marketing'), ('MGT', 'Management'), ('ACC', 'Accounting'), ('ECO', 'Economics'), ('PMGT', 'Public Management'), ('OM', 'Operations Management')], max_length=4)),
                ('has_kuwaiti_license', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-gpa', '-submitted_at'],
            },
        ),
    ]
