# Generated by Django 5.2.5 on 2025-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_parkingapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingapplication',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
