# Generated by Django 5.2.5 on 2025-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_parkingapplication_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingapplication',
            name='completed_credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
