# Generated by Django 5.2.5 on 2025-10-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_parkingapplication_completed_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, help_text='Show exchange program page to public')),
                ('coming_soon_message', models.TextField(blank=True, default='The Exchange Program is currently being prepared. Check back soon for exciting opportunities!', help_text='Message to display when exchange program is hidden')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Program Settings',
                'verbose_name_plural': 'Exchange Program Settings',
            },
        ),
    ]
