# Generated by Django 5.2.5 on 2025-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_exchangeprogramsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanlist',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='exchangeapplication',
            name='english_proficiency_document',
        ),
        migrations.RemoveField(
            model_name='exchangeapplication',
            name='passport_copy',
        ),
        migrations.RemoveField(
            model_name='exchangeapplication',
            name='transcript_document',
        ),
        migrations.RemoveField(
            model_name='partneruniversity',
            name='logo',
        ),
        migrations.AddField(
            model_name='partneruniversity',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to university logo image', max_length=500, null=True),
        ),
    ]
