# Generated by Django 5.2.5 on 2025-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_deanlist_excel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogramsettings',
            name='applications_closed_message',
            field=models.TextField(blank=True, default='Applications are currently closed. Please check back later for upcoming application periods.', help_text='Message to display when applications are disabled'),
        ),
        migrations.AddField(
            model_name='exchangeprogramsettings',
            name='applications_enabled',
            field=models.BooleanField(default=False, help_text='Allow students to submit exchange applications'),
        ),
    ]
