# Generated by Django 5.2.5 on 2025-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_exchangeprogramsettings_applications_closed_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogramsettings',
            name='document_form_embed_url',
            field=models.URLField(blank=True, help_text='Microsoft Forms embed URL for document uploads (e.g., https://forms.office.com/...)', null=True),
        ),
    ]
