# Generated by Django 5.2.5 on 2025-12-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_exchangeprogramsettings_document_form_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الجامعي')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم التواصل')),
                ('book_types', models.TextField(verbose_name='نوع الكتب اللي بيحب يقراها')),
                ('books_per_year', models.CharField(max_length=100, verbose_name='كم كتاب يقرأ تقريبًا بالسنة')),
                ('commitment_level', models.CharField(choices=[('COMMITTED', 'ملتزم'), ('MODERATE', 'نص نص'), ('NOT_COMMITTED', 'مو ملتزم بس اسعى لانتظام بالقراءة')], max_length=20, verbose_name='ما مدى التزامك بالقراءة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب انضمام لمجموعة القراءة',
                'verbose_name_plural': 'طلبات الانضمام لمجموعة القراءة',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
